# Generated by Django 5.1.5 on 2025-02-18 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.CharField(default=uuid.uuid4, help_text='Unique token for email verification.', max_length=64, null=True, unique=True),
        ),
    ]
