# Generated by Django 5.1.5 on 2025-02-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otp_attempts_user_otp_hash_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, help_text='Unique token for email verification.', max_length=64, null=True, unique=True),
        ),
    ]
